# Generated by Django 3.1.1 on 2020-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='excerpt',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='num_lessons',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(default='', upload_to='course_pictures'),
            preserve_default=False,
        ),
    ]
